version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: splitr-postgres
    restart: always
    environment:
      POSTGRES_USER: splitr_user
      POSTGRES_PASSWORD: splitr_pass
      POSTGRES_DB: splitr_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
